# Generated by Django 3.2.13 on 2023-05-17 02:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import movequotes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('MATCHING', '매칭전'), ('MATCHED', '매칭완료'), ('DEPOSIT', '입금완료'), ('PREPARING', '준비중'), ('COMPLETED', '완료')], default='MATCHING', max_length=20)),
                ('has_review', models.BooleanField(default=False)),
                ('size_type', models.CharField(choices=[('SMALL', '소형(20평미만)'), ('BIG', '대형(20평이상)')], default='SMALL', max_length=20)),
                ('packing_type', models.CharField(choices=[('PACKING', '포장'), ('NORMAL', '일반'), ('SEMIPACKING', '반포장')], default='PACKING', max_length=20)),
                ('customer_support', models.BooleanField(default=False)),
                ('start_info', models.JSONField(default=dict)),
                ('end_info', models.JSONField(default=dict)),
                ('luggage_info', models.JSONField(default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_move', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_move', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoveQuoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_comments', to='movequotes.movequote')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['amount'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MoveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=movequotes.models.get_upload_path)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_images', to='movequotes.movequote')),
            ],
        ),
        migrations.CreateModel(
            name='MoveQuoteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movequotes.movequote')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_reviews', to='accounts.company')),
            ],
            options={
                'unique_together': {('author', 'article')},
            },
        ),
    ]
